name: Android CD (Release)

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create build directory for keystore
        run: mkdir -p app/build

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          # O segredo a ser decodificado
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
          # O diretório onde o arquivo será salvo
          fileDir: 'app/build/'
          # O nome do arquivo a ser criado
          fileName: 'plaintextkotlin-release-key.jks'

      - name: Verify Keystore Location (Debug Step)
        run: |
          echo "Listing files in root directory:"
          ls -R

      - name: Build Signed Release APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: |
            Release gerada automaticamente pela action de CD.
          files: app/build/outputs/apk/release/app-release.apk